version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/terraformcode"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Kolkata"
    open-pull-requests-limit: 10 
    allow:
      - dependency-type: "all"